### ISSUE TITLE
Compatibility issue between current redis-monitoring-extension and machine agent version 20.5

### ISSUE THREAD

**Issue by YusukeMiyahara-A** [Appdynamics/redis-monitoring-extension#12]
Here is a stack trace:

```
[Agent-Monitor-Scheduler-3] 19 Oct 2020 20:37:43,484 INFO HealthCheckModule-Redis Enterprise Monitor - Running extension health checks

[Agent-Monitor-Scheduler-3] 19 Oct 2020 20:37:43,484 INFO PathResolver-Redis Enterprise Monitor - Install dir resolved to /opt/appd/appd_20.5.1/machineagent

[Agent-Monitor-Scheduler-3] 19 Oct 2020 20:37:43,494 ERROR PeriodicTaskRunner - Error creating environment task

java.lang.NoClassDefFoundError: org/apache/log4j/Layout

at com.appdynamics.extensions.conf.modules.HealthCheckModule.initMATroubleshootChecks(HealthCheckModule.java:80) ~[?:?]

at com.appdynamics.extensions.conf.MonitorContext.initialize(MonitorContext.java:93) ~[?:?]

at com.appdynamics.extensions.conf.MonitorContextConfiguration.setConfigYml(MonitorContextConfiguration.java:80) ~[?:?]

at com.appdynamics.extensions.ABaseMonitor$1.onFileChange(ABaseMonitor.java:132) ~[?:?]

at com.appdynamics.extensions.conf.modules.FileWatchListenerModule.createListener(FileWatchListenerModule.java:52) ~[?:?]

at com.appdynamics.extensions.conf.MonitorContextConfiguration.registerListener(MonitorContextConfiguration.java:146) ~[?:?]

at com.appdynamics.extensions.ABaseMonitor.initialize(ABaseMonitor.java:122) ~[?:?]

at com.appdynamics.extensions.ABaseMonitor.execute(ABaseMonitor.java:186) ~[?:?]

at com.singularity.ee.agent.systemagent.components.monitormanager.managed.MonitorTaskRunner.runTask(MonitorTaskRunner.java:149) ~[machineagent.jar:Machine Agent v20.5.1-2635 GA compatible with 4.4.1.0 Build Date 2020-05-27 21:53:51]

at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.runTask(PeriodicTaskRunner.java:86) ~[machineagent.jar:Machine Agent v20.5.1-2635 GA compatible with 4.4.1.0 Build Date 2020-05-27 21:53:51]

at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.run(PeriodicTaskRunner.java:47) [machineagent.jar:Machine Agent v20.5.1-2635 GA compatible with 4.4.1.0 Build Date 2020-05-27 21:53:51]

at com.singularity.ee.util.javaspecific.scheduler.AgentScheduledExecutorServiceImpl$SafeRunnable.run(AgentScheduledExecutorServiceImpl.java:122) [agent-4.5.13.2135.jar:?]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]

at com.singularity.ee.util.javaspecific.scheduler.ADFutureTask$Sync.innerRunAndReset(ADFutureTask.java:335) [agent-4.5.13.2135.jar:?]

at com.singularity.ee.util.javaspecific.scheduler.ADFutureTask.runAndReset(ADFutureTask.java:152) [agent-4.5.13.2135.jar:?]

at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.access$101(ADScheduledThreadPoolExecutor.java:119) [agent-4.5.13.2135.jar:?] at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.runPeriodic(ADScheduledThreadPoolExecutor.java:206) [agent-4.5.13.2135.jar:?] at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.run(ADScheduledThreadPoolExecutor.java:236) [agent-4.5.13.2135.jar:?]

at com.singularity.ee.util.javaspecific.scheduler.ADThreadPoolExecutor$Worker.runTask(ADThreadPoolExecutor.java:694) [agent-4.5.13.2135.jar:?]

at com.singularity.ee.util.javaspecific.scheduler.ADThreadPoolExecutor$Worker.run(ADThreadPoolExecutor.java:726) [agent-4.5.13.2135.jar:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]

Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Layout

at com.singularity.ee.util.loader.FileSystemClassLoader.findClass(FileSystemClassLoader.java:372) ~[agent-4.5.13.2135.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_261]

at com.singularity.ee.util.loader.FileSystemClassLoader.loadClass(FileSystemClassLoader.java:320) ~[agent-4.5.13.2135.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_261]

... 21 more
```

Here is a temporary workaround verified in my environment:

1. Download log4j-1.2.17.zip from here: 
http://www.apache.org/dyn/closer.cgi/logging/log4j/1.2.17/log4j-1.2.17.zip

2. Extract it and move the log4j-1.2.17.jar into /<machine-agent-dir>/monitors/RedisEnterpriseMonitor/log4j-1.2.17.jar

3. Edit the monitor.xml as below
`<classpath>redis-enterprise-monitoring-extension.jar;log4j-1.2.17.jar</classpath>
`
4. Run the machine agent as always

**Comment by YusukeMiyahara-A** [comment]
I mistakenly thought it was redis "enterprise" monitoring. Please delete this issue.

**Comment by phucpeta** [comment]
hello do you have redis-monitor.zip right now?
